# 자료구조 - Assignment 10 /20251221


---
## GRAPH

### Q05. 완전 그래프(모든 정점 사이에 간선이 존재) - 인접 행렬 vs 인접 리스트

**→ 인접 행렬(Adjacency Matrix)을 사용한다.**

**이유:**
-이유: 모든 정점 사이에 간선이 존재하는 완전 그래프이므로 간선 수가 최대 O(v**2)이다. 이 경우 인접 리스트의 공간 이점이 없으며, 인접행렬은 간섭 존재 여부를 O(1)에 확인할 수 있어 더 효율적이다

### Q06. 희소 그래프(Sparse Graph) - 인접 행렬 vs 인접 리스트

**→ 인접 리스트(Adjacency List)를 사용한다.**

**이유:**
-희소 그래프는 간선 수가 적으므로 인접 행렬의 많은 공간이 낭비된다. 인접 리스트는 실제 존재하는 간선만 저장하므로 공간 효율이 높아 O(V+E)의 공간만 사용한다

### Q08. DFS(1) 수행 시, v=1인 상태에서 DFS(x)가 호출되는 횟수

정점 1의 인접 정점(adj): **2, 4**

- DFS(1)이 호출되면 정점 1이 visited = YES로 표시된다.
- 이후 정점 1의 인접 정점들을 순서대로 순회하면서, **visited = NO인 인접 정점 x**에 대해 DFS(x)를 호출한다.
  - x = 2: visited = NO → DFS(2) 호출 (v=1에서 호출, 카운트 ✓)
  - x = 4: visited = NO → DFS(4) 호출 (v=1에서 호출, 카운트 ✓)

**→ 정점 1의 인접 정점 수 = 2개이므로, DFS(x)는 2번 호출된다.**

### Q12. 최소 신장 트리 (MST)

#### (1) 프림 알고리즘 (Prim's Algorithm)

**시작 정점: 임의의 정점 (예: 정점 1)**

프림 알고리즘은 현재 MST에 포함된 정점들에서 연결 가능한 간선 중 가중치가 가장 작은 간선을 선택하여 정점을 추가하는 방식

| 단계 | MST에 추가된 정점 | 선택된 간선         | 가중치 |
|------|-------------------|---------------------|--------|
| 1    | 1 (시작)          | -                   | -      |
| 2    | 4                 | (2, 4)              | 1      |
| 3    | 7                 | (4, 7)              | 2      |
| 4    | 6                 | (3, 6) 또는 (3,5)   | 3      |
| 5    | 5                 | (5, 7)              | 4      |
| 6    | 안                | (7, 안)             | 4      |
| 7    | 2                 | (1, 2)              | 8      |
| 8    | 3                 | (2, 3)              | 9      |

**MST 총 비용 = 1 + 2 + 3 + 4 + 4 + 8 + 9 = 31**



#### (2) 크루스칼 알고리즘 (Kruskal's Algorithm)

크루스칼 알고리즘은 **모든 간선을 가중치 오름차순으로 정렬**한 뒤, 사이클을 만들지 않는 간선을 순서대로 선택

**간선을 가중치 오름차순으로 정렬:**

| 간선      | 가중치 | 선택 여부 | 이유                  |
|-----------|--------|-----------|-----------------------|
| (2, 4)    | 1      | ✅ 선택   | 사이클 없음           |
| (4, 7)    | 2      | ✅ 선택   | 사이클 없음           |
| (3, 6)    | 3      | ✅ 선택   | 사이클 없음           |
| (5, 7)    | 4      | ✅ 선택   | 사이클 없음           |
| (7, 안)   | 4      | ✅ 선택   | 사이클 없음           |
| (3, 5)    | 5      | ❌ 제외   | 3-5-7 사이클 형성     |
| (6, 7)    | 7      | ❌ 제외   | 사이클 형성           |
| (1, 2)    | 8      | ✅ 선택   | 사이클 없음           |
| (3, 7)    | 8      | ❌ 제외   | 사이클 형성           |
| (6, 안)   | 8      | ❌ 제외   | 사이클 형성           |
| (2, 3)    | 9      | ✅ 선택   | 사이클 없음 (마지막)  |

**MST 총 비용 = 1 + 2 + 3 + 4 + 4 + 8 + 9 = 31**

### Q16. 위상 정렬 (Topological Sort) - STACK 사용

**그래프 구조 (방향 그래프):**
```
a → d → e
a → b
b → c
d → f → g
f → e
d → g
f → h  (또는 b → h)
```

#### STACK을 사용한 위상 정렬 수도 코드

```
TopologicalSort_Stack(G):
    모든 정점의 visited <- NO로 초기화
    STACK S 초기화
    
    for each 정점 v in G:
        if v.visited = NO:
            DFS_TS(v, S)
    
    while S is not empty:
        print S.pop()

DFS_TS(v, S):
    v.visited <- YES
    for each x ∈ v.adj:
        if x.visited = NO:
            DFS_TS(x, S)
    S.push(v)   ← DFS 완료 후 스택에 삽입
```

#### 가능한 위상 정렬 순서의 가짓수

**진입차수 분석:**
- a: 0
- b: a (1)
- c: b (1)
- d: a (1)
- e: d (1)
- f: d, e (2)
- g: f (1)
- h: f (1)

**풀이 과정:**

1. a는 진입차수가 0인 유일한 정점이므로 항상 첫 번째.
2. a 처리 후, b와 d가 모두 가능해지지만 두 가지를 어떤 순서로 배치할지는 자유롭다.
3. c는 항상 b 바로 다음에 와야 하고, e는 항상 d 바로 다음에 와야 한다. 즉 (b, c)와 (d, e)는 각각 묶음(쌍)으로 움직인다.
4. f는 d와 e가 모두 처리된 이후에만 가능하다.
5. f 처리 후, g와 h는 서로 순서에 영향을 주지 않으므로 2! = 2가지 순서가 가능하다.

**(b, c) 묶음과 (d, e) 묶음의 인터리빙:**

a 다음에 총 4개의 자리 중 2개를 (b, c) 묶음에, 나머지 2개를 (d, e) 묶음에 배정하는 방법의 수:

$$\binom{4}{2} = 6$$

**총 가짓수 = (b,c)와 (d,e)의 인터리빙(6) × f 이후 g,h의 순서(2) = 6 × 2 = 12가지**

### Q17. 다익스트라 알고리즘 (Dijkstra's Algorithm) - 시작 정점 s

**그래프 간선 정보:**

| 간선   | 가중치 |
|--------|--------|
| Q → A  | 10     |
| Q → C  | 7      |
| Q → E  | 4      |
| A → B  | 8      |
| C → A  | 2      |
| C → B  | 8      |
| C → E  | 2      |
| B → D  | 12     |
| D → F  | 7      |
| D → G  | 4      |
| F → C  | 12     |
| E ↔ F  | 8      |
| F ↔ G  | 3      |
| E → G  | 20     |

**시작 정점: Q**

초기: d[Q]=0, 나머지 = ∞

#### S 집합 (closed set) 순서:

| 순서 | S에 추가된 정점 |
|------|-----------------|
| 1    | Q               |
| 2    | E               |
| 3    | C               |
| 4    | A               |
| 5    | F               |
| 6    | B               |
| 7    | G               |
| 8    | D               |

#### d (거리) 테이블 갱신 과정:

| 단계      | Q | A | B  | C | D  | E | F  | G  |
|-----------|---|---|----|---|----|---|----|----|
| 초기      | 0 | ∞ | ∞  | ∞ | ∞  | ∞ | ∞  | ∞  |
| Q 처리    | 0 | 10| ∞  | 7 | ∞  | 4 | ∞  | ∞  |
| E 처리    | 0 | 10| ∞  | 7 | ∞  | 4 | 12 | 24 |
| C 처리    | 0 | 9 | 15 | 7 | ∞  | 4 | 12 | 24 |
| A 처리    | 0 | 9 | 15 | 7 | ∞  | 4 | 12 | 24 |
| F 처리    | 0 | 9 | 15 | 7 | ∞  | 4 | 12 | 15 |
| B 처리    | 0 | 9 | 15 | 7 | 27 | 4 | 12 | 15 |
| G 처리    | 0 | 9 | 15 | 7 | 27 | 4 | 12 | 15 |
| D 처리    | 0 | 9 | 15 | 7 | 27 | 4 | 12 | 15 |

**최단 거리 결과:**
- Q: 0, A: 9, B: 15, C: 7, D: 27, E: 4, F: 12, G: 15

### Q18. 다익스트라 알고리즘이 음의 가중치에서 작동하지 않는 예 (정점 3개)

**그래프 예시:**

```
정점: S, A, B
간선:
  S → A : 4
  S → B : 2
  B → A : -5
```

**다익스트라 알고리즘 수행:**

1. 초기: d[S]=0, d[A]=∞, d[B]=∞
2. S 처리 → d[A]=4, d[B]=2
3. B 처리 (d[B]=2가 최솟값) → B → A 이용: d[A] = min(4, 2 + (-5)) = **-3** 으로 갱신
   - 그런데 다익스트라는 이미 **A를 closed set에 넣기 전**에 d[A]=4로 확정했다면 갱신 불가
4. A 처리 (d[A]=4로 확정) → **실제 최단 거리 -3을 놓침**

**문제 발생 이유:**
- 다익스트라는 한 번 S 집합에 추가된 정점의 거리는 최종 확정으로 간주한다.
- 그러나 음의 가중치 간선이 있으면 나중에 더 짧은 경로가 발견될 수 있어, 이미 확정된 거리가 틀릴 수 있다.
- 따라서 **음의 가중치가 있는 그래프에서는 다익스트라 알고리즘이 올바른 최단 경로를 보장하지 못한다.**

### Q22. 벨만-포드 알고리즘에서 답을 구할 수 없는 경우

**→ 그래프에 음의 사이클(Negative Cycle)이 존재하는 경우**

**설명:**
- 벨만-포드 알고리즘은 음의 가중치가 있는 그래프에서도 최단 경로를 구할 수 있다.
- 그러나 **음의 사이클(가중치 합이 음수인 사이클)** 이 존재하면, 그 사이클을 계속 돌수록 경로 비용이 -∞로 발산한다.
- 이 경우 최단 경로가 정의되지 않으므로 답을 구할 수 없다.
- 벨만-포드 알고리즘은 V-1번의 릴렉세이션 후 한 번 더 수행하여, 거리가 갱신되면 음의 사이클이 존재함을 감지한다.

**예시:**
```
A → B : 1
B → C : -3
C → A : 1
사이클 합: 1 + (-3) + 1 = -1 < 0  → 음의 사이클 존재 → 답 없음
```

---
## SORTING

### Q05. 원소: 12 70 30 20 55 25

#### (1) 선택 정렬 (Selection Sort)

매 단계에서 **미정렬 부분의 최솟값**을 찾아 맨 앞으로 이동한다.

| 단계 | 배열 상태                  | 선택(최솟값) | 교환            |
|------|----------------------------|--------------|------------------|
| 초기 | **12** 70 30 20 55 25      | -            | -                |
| 1    | [12] **70** 30 20 55 25    | 12 (index 0) | 교환 없음        |
| 2    | [12 20] **30** 70 55 25    | 20 (index 3) | 70 ↔ 20          |
| 3    | [12 20 25] 70 55 **30**    | 25 (index 5) | 30 ↔ 25          |
| 4    | [12 20 25 30] 55 **70**    | 30 (index 3) | 70 ↔ 30          |
| 5    | [12 20 25 30 55] **70**    | 55 (index 4) | 교환 없음        |
| 결과 | 12 20 25 30 55 70          |              |                  |

**단계별 상세 과정:**
```
초기:  12  70  30  20  55  25
1회:  [12] 70  30  20  55  25   → 최솟값 12, 교환 없음
2회:  [12  20] 30  70  55  25   → 최솟값 20(위치3), 70↔20
3회:  [12  20  25] 70  55  30   → 최솟값 25(위치5), 30↔25
4회:  [12  20  25  30] 55  70   → 최솟값 30(위치5→3), 70↔30
5회:  [12  20  25  30  55] 70   → 최솟값 55, 교환 없음
결과:  12  20  25  30  55  70
```

#### (2) 버블 정렬 (Bubble Sort)

인접한 두 원소를 비교하여 순서가 잘못된 경우 교환한다. 매 패스마다 가장 큰 값이 맨 뒤로 이동한다.

```
초기:   12  70  30  20  55  25

[Pass 1]
  12  70  30  20  55  25
  12  30  70  20  55  25   → 70 > 30, 교환
  12  30  20  70  55  25   → 70 > 20, 교환
  12  30  20  55  70  25   → 70 > 55, 교환
  12  30  20  55  25  70   → 70 > 25, 교환
  → Pass 1 결과: 12  30  20  55  25  [70]

[Pass 2]
  12  30  20  55  25  [70]
  12  20  30  55  25  [70]  → 30 > 20, 교환
  12  20  30  55  25  [70]  → 교환 없음
  12  20  30  25  55  [70]  → 55 > 25, 교환
  → Pass 2 결과: 12  20  30  25  [55  70]

[Pass 3]
  12  20  30  25  [55  70]
  12  20  25  30  [55  70]  → 30 > 25, 교환
  → Pass 3 결과: 12  20  25  [30  55  70]

[Pass 4]
  12  20  25  [30  55  70]  → 교환 없음
  → Pass 4 결과: 12  20  [25  30  55  70]

[Pass 5]
  12  20  [25  30  55  70]  → 교환 없음
  → 완료

결과:  12  20  25  30  55  70
```

#### (3) 삽입 정렬 (Insertion Sort)

두 번째 원소부터 시작하여 앞쪽 정렬된 부분에 올바른 위치로 삽입한다.

```
초기:  12  70  30  20  55  25

i=1: key=70
  [12  70]  30  20  55  25   → 12 < 70, 삽입 위치 확정
  결과: 12  70  30  20  55  25

i=2: key=30
  [12  70]  → 70 > 30, 70 오른쪽으로 이동
  [12  __ 70] → 12 < 30, 삽입
  결과: 12  30  70  20  55  25

i=3: key=20
  [12  30  70] → 70 > 20, 이동 / 30 > 20, 이동 / 12 < 20, 삽입
  결과: 12  20  30  70  55  25

i=4: key=55
  [12  20  30  70] → 70 > 55, 이동 / 30 < 55, 삽입
  결과: 12  20  30  55  70  25

i=5: key=25
  [12  20  30  55  70] → 70>25, 55>25, 30>25, 20<25, 삽입
  결과: 12  20  25  30  55  70

최종 결과:  12  20  25  30  55  70
```

### Q06. 원소: 12 70 30 20 55 25 40 50

#### (2) 힙 정렬 (Heap Sort)

**1단계: 최대 힙(Max-Heap) 구성 (heapify)**

배열 인덱스 0~7: [12, 70, 30, 20, 55, 25, 40, 50]

```
초기 배열을 힙으로 표현:
              12(0)
           /         \
        70(1)         30(2)
       /    \        /    \
    20(3)  55(4)  25(5)  40(6)
    /
  50(7)

내부 노드(index 3→0)에 대해 sift-down 수행:

index=3: [20, 50] → 50>20, 교환 → [50이 3번]
  배열: [12, 70, 30, 50, 55, 25, 40, 20]

index=2: [30, 25, 40] → 40>30, 교환 → [40이 2번]
  배열: [12, 70, 40, 50, 55, 25, 30, 20]

index=1: [70, 50, 55] → 70이 최대, 교환 없음
  배열: [12, 70, 40, 50, 55, 25, 30, 20]

index=0: [12, 70, 40] → 70>12, 교환
  배열: [70, 12, 40, 50, 55, 25, 30, 20]
  이후 12이 내려가며: [12, 50, 55] → 55>12, 교환
  배열: [70, 55, 40, 50, 12, 25, 30, 20]
  이후 12이 내려가며: [12, 20] → 20>12, 교환
  배열: [70, 55, 40, 50, 20, 25, 30, 12]

Max-Heap 완성: [70, 55, 40, 50, 20, 25, 30, 12]
```

**2단계: 정렬 (힙에서 최댓값 추출 반복)**

```
힙: [70, 55, 40, 50, 20, 25, 30, 12]

추출1: 70↔12 교환 → [12, 55, 40, 50, 20, 25, 30 | 70]
  sift-down(0): 55>40, 12↔55 → [55, 12, 40, 50, 20, 25, 30]
               50>20, 12↔50 → [55, 50, 40, 12, 20, 25, 30]
  힙: [55, 50, 40, 12, 20, 25, 30, 12] (정렬부분 제외)

추출2: 55↔30 교환 → [30, 50, 40, 12, 20, 25 | 55, 70]
  sift-down: 50>40, 30↔50 → [50, 30, 40, 12, 20, 25]
             30↔20 없음 (30>20)
  힙: [50, 30, 40, 12, 20, 25]

추출3: 50↔25 교환 → [25, 30, 40, 12, 20 | 50, 55, 70]
  sift-down: 40>30, 25↔40 → [40, 30, 25, 12, 20]
  힙: [40, 30, 25, 12, 20]

추출4: 40↔20 교환 → [20, 30, 25, 12 | 40, 50, 55, 70]
  sift-down: 30>25, 20↔30 → [30, 20, 25, 12]
  힙: [30, 20, 25, 12]

추출5: 30↔12 교환 → [12, 20, 25 | 30, 40, 50, 55, 70]
  sift-down: 25>20, 12↔25 → [25, 20, 12]
  힙: [25, 20, 12]

추출6: 25↔12 교환 → [12, 20 | 25, 30, 40, 50, 55, 70]
  sift-down: 20>12, 12↔20 → [20, 12]

추출7: 20↔12 교환 → [12 | 20, 25, 30, 40, 50, 55, 70]

최종 결과: 12  20  25  30  40  50  55  70
```

#### (3) 퀵 정렬 (Quick Sort)

**피벗(pivot): 배열의 첫 번째 원소 사용**

```
초기: [12  70  30  20  55  25  40  50]

--- 1차 분할: pivot = 12 ---
pivot=12: 12보다 작은 원소 없음
  → 왼쪽: [] | 12 | 오른쪽: [70  30  20  55  25  40  50]
  결과: [12 | 70  30  20  55  25  40  50]

--- 오른쪽 [70  30  20  55  25  40  50] 분할: pivot = 70 ---
pivot=70: 70보다 큰 원소 없음
  왼쪽: [30  20  55  25  40  50] | 70 | 오른쪽: []

--- [30  20  55  25  40  50] 분할: pivot = 30 ---
  왼쪽 (< 30): [20  25]
  오른쪽 (> 30): [55  40  50]
  결과: [20  25 | 30 | 55  40  50]

--- [20  25] 분할: pivot = 20 ---
  왼쪽: [] | 20 | 오른쪽: [25]
  결과: [20  25]

--- [55  40  50] 분할: pivot = 55 ---
  왼쪽 (< 55): [40  50]
  오른쪽 (> 55): []
  결과: [40  50 | 55]

--- [40  50] 분할: pivot = 40 ---
  왼쪽: [] | 40 | 오른쪽: [50]
  결과: [40  50]

--- 최종 병합 ---
[12] + [20  25] + [30] + [40  50] + [55] + [70]
= 12  20  25  30  40  50  55  70

최종 결과: 12  20  25  30  40  50  55  70
```